// Copyright © 2019 Binance
//
// This file is part of Binance. The full Binance copyright notice, including
// terms governing use, modification, and redistribution, is contained in the
// file LICENSE at the root of the source code distribution tree.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.1
// source: protob/signature.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Container for output signatures, mostly used for marshalling this data structure to a mobile app
type SignatureData struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Signature []byte                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"`
	// Ethereum-style recovery byte; only the first byte is relevant
	SignatureRecovery []byte `protobuf:"bytes,2,opt,name=signature_recovery,json=signatureRecovery,proto3" json:"signature_recovery,omitempty"`
	// Signature components R, S
	R []byte `protobuf:"bytes,3,opt,name=r,proto3" json:"r,omitempty"`
	S []byte `protobuf:"bytes,4,opt,name=s,proto3" json:"s,omitempty"`
	// M represents the original message digest that was signed M
	M             []byte                      `protobuf:"bytes,5,opt,name=m,proto3" json:"m,omitempty"`
	OneRoundData  *SignatureData_OneRoundData `protobuf:"bytes,11,opt,name=one_round_data,json=oneRoundData,proto3" json:"one_round_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignatureData) Reset() {
	*x = SignatureData{}
	mi := &file_protob_signature_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignatureData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignatureData) ProtoMessage() {}

func (x *SignatureData) ProtoReflect() protoreflect.Message {
	mi := &file_protob_signature_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignatureData.ProtoReflect.Descriptor instead.
func (*SignatureData) Descriptor() ([]byte, []int) {
	return file_protob_signature_proto_rawDescGZIP(), []int{0}
}

func (x *SignatureData) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignatureData) GetSignatureRecovery() []byte {
	if x != nil {
		return x.SignatureRecovery
	}
	return nil
}

func (x *SignatureData) GetR() []byte {
	if x != nil {
		return x.R
	}
	return nil
}

func (x *SignatureData) GetS() []byte {
	if x != nil {
		return x.S
	}
	return nil
}

func (x *SignatureData) GetM() []byte {
	if x != nil {
		return x.M
	}
	return nil
}

func (x *SignatureData) GetOneRoundData() *SignatureData_OneRoundData {
	if x != nil {
		return x.OneRoundData
	}
	return nil
}

// Elliptic curve point representation
type ECPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             []byte                 `protobuf:"bytes,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             []byte                 `protobuf:"bytes,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ECPoint) Reset() {
	*x = ECPoint{}
	mi := &file_protob_signature_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ECPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ECPoint) ProtoMessage() {}

func (x *ECPoint) ProtoReflect() protoreflect.Message {
	mi := &file_protob_signature_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ECPoint.ProtoReflect.Descriptor instead.
func (*ECPoint) Descriptor() ([]byte, []int) {
	return file_protob_signature_proto_rawDescGZIP(), []int{1}
}

func (x *ECPoint) GetX() []byte {
	if x != nil {
		return x.X
	}
	return nil
}

func (x *ECPoint) GetY() []byte {
	if x != nil {
		return x.Y
	}
	return nil
}

// One-round signing data (for offline/async signing)
type SignatureData_OneRoundData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sanity check in FinalizeGetAndVerifyFinalSig
	T int32 `protobuf:"varint,1,opt,name=t,proto3" json:"t,omitempty"`
	// Components to produce s = sum(s_i)
	KI      []byte   `protobuf:"bytes,2,opt,name=k_i,json=kI,proto3" json:"k_i,omitempty"`
	RSigmaI []byte   `protobuf:"bytes,3,opt,name=r_sigma_i,json=rSigmaI,proto3" json:"r_sigma_i,omitempty"`
	BigR    *ECPoint `protobuf:"bytes,4,opt,name=big_r,json=bigR,proto3" json:"big_r,omitempty"`
	// Components for identifiable aborts during the final phase
	BigRBarJ      map[string]*ECPoint `protobuf:"bytes,5,rep,name=big_r_bar_j,json=bigRBarJ,proto3" json:"big_r_bar_j,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	BigSJ         map[string]*ECPoint `protobuf:"bytes,6,rep,name=big_s_j,json=bigSJ,proto3" json:"big_s_j,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignatureData_OneRoundData) Reset() {
	*x = SignatureData_OneRoundData{}
	mi := &file_protob_signature_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignatureData_OneRoundData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignatureData_OneRoundData) ProtoMessage() {}

func (x *SignatureData_OneRoundData) ProtoReflect() protoreflect.Message {
	mi := &file_protob_signature_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignatureData_OneRoundData.ProtoReflect.Descriptor instead.
func (*SignatureData_OneRoundData) Descriptor() ([]byte, []int) {
	return file_protob_signature_proto_rawDescGZIP(), []int{0, 0}
}

func (x *SignatureData_OneRoundData) GetT() int32 {
	if x != nil {
		return x.T
	}
	return 0
}

func (x *SignatureData_OneRoundData) GetKI() []byte {
	if x != nil {
		return x.KI
	}
	return nil
}

func (x *SignatureData_OneRoundData) GetRSigmaI() []byte {
	if x != nil {
		return x.RSigmaI
	}
	return nil
}

func (x *SignatureData_OneRoundData) GetBigR() *ECPoint {
	if x != nil {
		return x.BigR
	}
	return nil
}

func (x *SignatureData_OneRoundData) GetBigRBarJ() map[string]*ECPoint {
	if x != nil {
		return x.BigRBarJ
	}
	return nil
}

func (x *SignatureData_OneRoundData) GetBigSJ() map[string]*ECPoint {
	if x != nil {
		return x.BigSJ
	}
	return nil
}

var File_protob_signature_proto protoreflect.FileDescriptor

const file_protob_signature_proto_rawDesc = "" +
	"\n" +
	"\x16protob/signature.proto\x12\x0ebinance.tsslib\"\xa3\x05\n" +
	"\rSignatureData\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\fR\tsignature\x12-\n" +
	"\x12signature_recovery\x18\x02 \x01(\fR\x11signatureRecovery\x12\f\n" +
	"\x01r\x18\x03 \x01(\fR\x01r\x12\f\n" +
	"\x01s\x18\x04 \x01(\fR\x01s\x12\f\n" +
	"\x01m\x18\x05 \x01(\fR\x01m\x12P\n" +
	"\x0eone_round_data\x18\v \x01(\v2*.binance.tsslib.SignatureData.OneRoundDataR\foneRoundData\x1a\xc8\x03\n" +
	"\fOneRoundData\x12\f\n" +
	"\x01t\x18\x01 \x01(\x05R\x01t\x12\x0f\n" +
	"\x03k_i\x18\x02 \x01(\fR\x02kI\x12\x1a\n" +
	"\tr_sigma_i\x18\x03 \x01(\fR\arSigmaI\x12,\n" +
	"\x05big_r\x18\x04 \x01(\v2\x17.binance.tsslib.ECPointR\x04bigR\x12W\n" +
	"\vbig_r_bar_j\x18\x05 \x03(\v28.binance.tsslib.SignatureData.OneRoundData.BigRBarJEntryR\bbigRBarJ\x12M\n" +
	"\abig_s_j\x18\x06 \x03(\v25.binance.tsslib.SignatureData.OneRoundData.BigSJEntryR\x05bigSJ\x1aT\n" +
	"\rBigRBarJEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.binance.tsslib.ECPointR\x05value:\x028\x01\x1aQ\n" +
	"\n" +
	"BigSJEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.binance.tsslib.ECPointR\x05value:\x028\x01\"%\n" +
	"\aECPoint\x12\f\n" +
	"\x01x\x18\x01 \x01(\fR\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\fR\x01yB\n" +
	"Z\b./commonb\x06proto3"

var (
	file_protob_signature_proto_rawDescOnce sync.Once
	file_protob_signature_proto_rawDescData []byte
)

func file_protob_signature_proto_rawDescGZIP() []byte {
	file_protob_signature_proto_rawDescOnce.Do(func() {
		file_protob_signature_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protob_signature_proto_rawDesc), len(file_protob_signature_proto_rawDesc)))
	})
	return file_protob_signature_proto_rawDescData
}

var file_protob_signature_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_protob_signature_proto_goTypes = []any{
	(*SignatureData)(nil),              // 0: binance.tsslib.SignatureData
	(*ECPoint)(nil),                    // 1: binance.tsslib.ECPoint
	(*SignatureData_OneRoundData)(nil), // 2: binance.tsslib.SignatureData.OneRoundData
	nil,                                // 3: binance.tsslib.SignatureData.OneRoundData.BigRBarJEntry
	nil,                                // 4: binance.tsslib.SignatureData.OneRoundData.BigSJEntry
}
var file_protob_signature_proto_depIdxs = []int32{
	2, // 0: binance.tsslib.SignatureData.one_round_data:type_name -> binance.tsslib.SignatureData.OneRoundData
	1, // 1: binance.tsslib.SignatureData.OneRoundData.big_r:type_name -> binance.tsslib.ECPoint
	3, // 2: binance.tsslib.SignatureData.OneRoundData.big_r_bar_j:type_name -> binance.tsslib.SignatureData.OneRoundData.BigRBarJEntry
	4, // 3: binance.tsslib.SignatureData.OneRoundData.big_s_j:type_name -> binance.tsslib.SignatureData.OneRoundData.BigSJEntry
	1, // 4: binance.tsslib.SignatureData.OneRoundData.BigRBarJEntry.value:type_name -> binance.tsslib.ECPoint
	1, // 5: binance.tsslib.SignatureData.OneRoundData.BigSJEntry.value:type_name -> binance.tsslib.ECPoint
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_protob_signature_proto_init() }
func file_protob_signature_proto_init() {
	if File_protob_signature_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protob_signature_proto_rawDesc), len(file_protob_signature_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protob_signature_proto_goTypes,
		DependencyIndexes: file_protob_signature_proto_depIdxs,
		MessageInfos:      file_protob_signature_proto_msgTypes,
	}.Build()
	File_protob_signature_proto = out.File
	file_protob_signature_proto_goTypes = nil
	file_protob_signature_proto_depIdxs = nil
}
